<myLayout>
    BoxLayout:
        orientation: "horizontal"
        size: root.width, root.height
        spacing : 20
        padding: 20

        Button:
            text: "BoxLayout 1"
        Button:
            text: "BoxLayout 2"
        Button:
            text: "BoxLayout 3"
            pos_hint: {'center_x': .5 }
            size_hint: (None,None)
            width: 100
            height: 50
       